### ISSUE TITLE
Feature Request: Custom CSS

### ISSUE THREAD

**Issue by jbaum98** [joshuacaron/markdown#2]
The user can, in the settings, specify custom css to be used when rendering output.

**Comment by joshuacaron** [comment]
Hi, thanks for your feedback again. There are a few things that might cause problems with this such as if the user radically changes line spacing and font sizes, or other spacing things, then the synchronized scrolling could potentially be out of sync. It could definitely be interesting though so I'll think more about it as I port the code base over to Polymer 1.0. I will probably end up adding it (as a user beware kind of a feature), but porting the code base to Polymer 1.0 is my priority for now so it might be a little while before I get to this. I will keep you informed. Thanks!

**Comment by joshuacaron** [comment]
Okay I implemented a custom CSS field into the settings. The updated version should be on the Chrome Webstore in an hour or so. Thanks for the feedback.

**Comment by jbaum98** [comment]
Thanks so much for the quick response!
